CREATE TABLE
  accounts (
    id TEXT NOT NULL, -- account identifier (external, user-defined)
    bucket TEXT NOT NULL, -- bucket / balance / color
    asset TEXT NOT NULL, -- currency + precision, e.g. USD/2
    in_volume BIGINT NOT NULL DEFAULT 0,
    out_volume BIGINT NOT NULL DEFAULT 0,
    last_transfer_id BIGINT NULL, -- last applied transfer (snowflake)
    PRIMARY KEY (id, bucket, asset)
  );

CREATE TABLE
  transfers (
    id BIGINT NOT NULL, -- snowflake, generated by application
    src TEXT NOT NULL, -- source account id
    dst TEXT NOT NULL, -- destination account id
    src_bucket TEXT NULL, -- NULL = ephemeral
    dst_bucket TEXT NULL, -- NULL = ephemeral
    asset TEXT NOT NULL,
    amount BIGINT NOT NULL, -- minimal units
    -- snapshots AFTER transfer
    src_bucket_in_volume BIGINT NULL, -- NULL = ephemeral
    src_bucket_out_volume BIGINT NULL, -- NULL = ephemeral
    dst_bucket_in_volume BIGINT NULL, -- NULL = ephemeral
    dst_bucket_out_volume BIGINT NULL, -- NULL = ephemeral
    created_at TIMESTAMP NOT NULL DEFAULT now ()
  );