[workspace]
resolver = "3"
members = [
  "crates/sql-client",
  "crates/ext-core",
  "crates/lib-money",
  "crates/host",
  "crates/tx",
  "crates/utils",
]

[workspace.dependencies]
wit-bindgen = "0.51.0"
wasmtime = "42.0.0"
wasmtime-wasi = "42.0.0"
wasmledger-sql-client = { path = "crates/sql-client" }
wasmledger-utils = { path = "crates/utils" }
