package wasmledger:plugin;

interface migrations {
  use wasmledger:sql/query.{query-executor};
  use wasmledger:sql/util-types.{error};

  type migration-id = string;

  variant schema-error {
    schema-invalid(string),
    sql(error)
  }

  get-migration-group: func() -> string;

  list-migrations: async func() -> list<migration-id>;
  apply-migration: async func(id: migration-id, executor: query-executor) -> result<_, error>;

  check-schema: async func(executor: query-executor) -> result<_, schema-error>;
}