package wasmledger:extension@0.1.0;

interface migration {
    record migration {
        id: string,
        sql: string,
    }

    extension-id: func() -> string;
    get-migrations: func() -> list<migration>;
}
